export const routeConstants = {
  MAIN: 'MAIN',
  // ** root screens **
  SPLASH: 'SPLASH',
  APP_LOADING: 'APP_LOADING',
  // email-verification
  EMAIL_VERIFICATION: 'EMAIL_VERIFICATION',
  // error screens
  ERROR_SERVER: 'ERROR_SERVER',
  ERROR_SERVICE_UNAVAILABLE: 'ERROR_SERVICE_UNAVAILABLE',
  ERROR_SETUP: 'ERROR_SETUP',
  ERROR_UPGRADE: 'ERROR_UPGRADE',
  // account Screens
  ACCOUNT_DEPOSIT_DETAILS_WAITING: 'ACCOUNT_DEPOSIT_DETAILS_WAITING',
  ACCOUNT_DEPOSIT_PREVIEW_NOTICE: 'ACCOUNT_DEPOSIT_PREVIEW_NOTICE',
  ACCOUNT_INFORMATION: 'ACCOUNT_INFORMATION',
  // verification
  IDENTITY_VERIFICATION: 'IDENTITY_VERIFICATION',
  // account initalise
  ACCOUNT_INITIALISE: 'ACCOUNT_INITIALISE',
  // product
  PRODUCT_DETAIL: 'PRODUCT_DETAIL',
  // verification
  VERIFICATION_STATUS: 'VERIFICATION_STATUS',
  // local auth
  LOCAL_AUTHENTICATION: 'LOCAL_AUTHENTICATION',
  LOCAL_AUTHENTICATION_ENABLE: 'LOCAL_AUTHENTICATION_ENABLE',
  // user blocked
  BLOCKED_USER: 'BLOCKED_USER',
  BLOCKED_USER_LOCATION: 'BLOCKED_USER_LOCATION',

  // dev screens
  DEV_MENU: 'DEV_MENU',
  // ** nested screens **

  // tabs - Tab Navigator
  TABS: 'TABS',
  TAB_DISCOVERY: 'TAB_DISCOVERY',
  TAB_ACCOUNTS: 'TAB_ACCOUNTS',
  TAB_PORTFOLIO: 'TAB_PORTFOLIO',
  TAB_PROFILE: 'TAB_PROFILE',

  // sign-up - Stack Navigator
  SIGN_UP: 'SIGN_UP',
  SIGN_UP_NAME: 'SIGN_UP_NAME',
  SIGN_UP_NATIONALITY: 'SIGN_UP_NATIONALITY',
  SIGN_UP_CONSENT: 'SIGN_UP_CONSENT',
  SIGN_UP_BIRTHDAY: 'SIGN_UP_BIRTHDAY',
  SIGN_UP_LOCATION: 'SIGN_UP_LOCATION',

  // address-verification - Stack Navigator
  ADDRESS_VERIFICATION: 'ADDRESS_VERIFICATION',
  ADDRESS_VERIFICATION_ENTRY: 'ADDRESS_VERIFICATION_ENTRY',
  ADDRESS_VERIFICATION_DECLINE: 'ADDRESS_VERIFICATION_DECLINE',
  ADDRESS_VERIFICATION_CONFIRMATION: 'ADDRESS_VERIFICATION_CONFIRMATION',
  ADDRESS_VERIFICATION_REQUEST_POSTAL_DELIVERY:
    'ADDRESS_VERIFICATION_REQUEST_POSTAL_DELIVERY',
  ADDRESS_VERIFICATION_WAITING_POSTAL_DELIVERY:
    'ADDRESS_VERIFICATION_WAITING_POSTAL_DELIVERY',

  // name-change - Stack Navigator
  NAME_CHANGE: 'NAME_CHANGE',
  NAME_CHANGE_ENTRY: 'NAME_CHANGE_ENTRY',
  NAME_CHANGE_SUCCESS: 'NAME_CHANGE_SUCCESS',

  // questionnaire - Stack Navigator
  QUESTIONNAIRE: 'QUESTIONNAIRE',
  QUESTIONNAIRE_TAX_RESIDENCY: 'QUESTIONNAIRE_TAX_RESIDENCY',
  QUESTIONNAIRE_TRADING_PURPOSE: 'QUESTIONNAIRE_TRADING_PURPOSE',

  // Modals - Modal Navigator
  MODALS: 'MODALS',
  MODAL_ERROR: 'MODAL_ERROR',
  ADD_ACCOUNT: 'ADD_ACCOUNT',
  BASE_CURRENCY_CHANGE: 'BASE_CURRENCY_CHANGE',
  BASE_LANGUAGE_CHANGE: 'BASE_LANGUAGE_CHANGE',

  // Withdraw Fiat
  WITHDRAW_FIAT: 'WITHDRAW_FIAT',
  WITHDRAW_FIAT_SOURCE: 'WITHDRAW_FIAT_SOURCE',
  WITHDRAW_FIAT_REFERENCE: 'WITHDRAW_FIAT_REFERENCE',
  WITHDRAW_FIAT_DETAILS: 'WITHDRAW_FIAT_DETAILS',
  WITHDRAW_FIAT_AMOUNT: 'WITHDRAW_FIAT_AMOUNT',
  WITHDRAW_FIAT_CONFIRM: 'WITHDRAW_FIAT_CONFIRM',
  WITHDRAW_FIAT_SUCCESS: 'WITHDRAW_FIAT_SUCCESS',

  // Deposit Fiat
  DEPOSIT_FIAT: 'DEPOSIT_FIAT',
  DEPOSIT_FIAT_SOURCE: 'DEPOSIT_FIAT_SOURCE',
  DEPOSIT_FIAT_WARNING: 'DEPOSIT_FIAT_WARNING',
  DEPOSIT_FIAT_DETAILS: 'DEPOSIT_FIAT_DETAILS',

  // Transfer Fiat
  TRANSFER_FIAT: 'TRANSFER_FIAT',
  TRANSFER_FIAT_SOURCE: 'TRANSFER_FIAT_SOURCE',
  TRANSFER_FIAT_DESTINATION: 'TRANSFER_FIAT_DESTINATION',
  TRANSFER_FIAT_AMOUNT: 'TRANSFER_FIAT_AMOUNT',
  TRANSFER_FIAT_CONFIRM: 'TRANSFER_FIAT_CONFIRM',
  TRANSFER_FIAT_SUCCESS: 'TRANSFER_FIAT_SUCCESS',

  // Trade Fiat
  TRADE_FIAT: 'TRADE_FIAT',
  TRADE_FIAT_SOURCE: 'TRADE_FIAT_SOURCE',
  TRADE_FIAT_DESTINATION: 'TRADE_FIAT_DESTINATION',
  TRADE_FIAT_AMOUNT: 'TRADE_FIAT_AMOUNT',
  TRADE_FIAT_CONFIRM: 'TRADE_FIAT_CONFIRM',
  TRADE_FIAT_SUCCESS: 'TRADE_FIAT_SUCCESS',

  // Trade Crypto
  TRADE_CRYPTO: 'TRADE_CRYPTO',
  TRADE_CRYPTO_SOURCE: 'TRADE_CRYPTO_SOURCE',
  TRADE_CRYPTO_AMOUNT: 'TRADE_CRYPTO_AMOUNT',
  TRADE_CRYPTO_CONFIRM: 'TRADE_CRYPTO_CONFIRM',
  TRADE_CRYPTO_SUCCESS: 'TRADE_CRYPTO_SUCCESS'
} as const;

export type RouteConstantsKeys = keyof typeof routeConstants;
export type RouteConstantValues = typeof routeConstants[RouteConstantsKeys];
